#!/usr/bin/env bash
# write a Bash script that will display information about the subdomains

subdomains=( "www" "lb-01" "web-01" "web-02" )

domain="$1"

sub="$2"



config_domain() {

# func variables

sub="$2"

DOM_INFO="$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | awk 'NR==2')"

IP=$(echo "$DOM_INFO" | awk '{print $5}')

RECORD=$(echo "$DOM_INFO" | awk '{print $4}')



echo -e "The subdomain $sub is a $RECORD record and points to $IP"

}



if [ $# -eq 1 ]; then

for subs in "${subdomains[@]}"; do

config_domain "$domain" "$subs"

done

elif [ $# -eq 2 ]; then

config_domain "$domain" "$sub"

fi

