#!/usr/bin/env bash
# Configure Nginx server
# Use sudo to run the following command as root
# Install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Allow incoming traffic for Nginx HTTP
sudo ufw allow 'Nginx HTTP'

# Create the directory for the website's HTML files if it doesn't exist
# -p flag creates the parent directories if needed
sudo mkdir -p /var/www/html 

# Set permissions for the directory and its contents
# 755 is a common permission set for directories (read, write, execute for owner, read and execute for group and others)
sudo chmod -R 755 /var/www/html

# Create a simple "Hello World!" index file in the HTML directory
# The > operator redirects the output of the command to the specified file
echo 'Hello World!' | sudo tee  /var/www/html/index.html


# add the following configuration to the existing server block
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.google.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Create a custom 404 error page in the HTML directory
echo "Ceci n'est pas une page" | sudo tee  /var/www/html/404.html
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-available/default



# Use sed to edit the Nginx configuration file in-placeSearch for the line 
# that starts with "http {" and add a new line after it the path to the Nginx configuration file
# code for http_response_header
sudo sed -i '/^http {/a \\tadd_header X-Served-By $hostname;' /etc/nginx/nginx.conf


# Reload Nginx
sudo service nginx restart
