#!/usr/bin/env bash

# Update the package list to include the HAProxy PPA
sudo apt-get update -y

# Install HAProxy
sudo apt-get install haproxy -y

# Add the HAProxy configuration to the new file
echo "
frontend web-frontend
	bind *:80
	mode http
	default_backend web-backend

backend web-backend
	balance roundrobin
	server 120281-web-01 100.26.174.161:80 check
	server 120281-web-02 35.175.126.31:80 check
" >>  /etc/haproxy/haproxy.cfg



# Enable HAProxy in the system startup

sudo sed -i  's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy


# Start the HAProxy service
sudo service haproxy restart
