#!/usr/bin/env bash
# Installs and configure HAproxy on the lb-01 server
# using roundrobin algorithm

sudo apt-get update -y
sudo apt-get install haproxy -y

# Configure HAProxy using roundrobin algorithm
echo "
frontend web-frontend
	bind *:80
	mode http
	default_backend web-backend

backend web-backend
	balance roundrobin
	server 120281-web-01 54.165.42.169:80 check
	server 120281-web-02 54.175.145.139:80 check
" >>  /etc/haproxy/haproxy.cfg

# Enable HAProxy management

sudo sed -i  's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy


# Start the HAProxy service
sudo service haproxy restart
