#!/usr/bin/env bash


# Write a Bash script that displays the content of the file /etc/passwd.

# Your script should only display:

    # username
    # user id
    # Home directory path for the user

# Requirements:

    # You must use the while loop (for and until are forbidden)

while read -r line
do
    username=$(echo $line | cut -d: -f1)
    user_id=$(echo $line | cut -d: -f3)
    home_dir=$(echo $line | cut -d: -f6)
    echo "Username: $username"
    echo "User ID: $user_id"
    echo "Home directory path: $home_dir"
    echo ""
done < /etc/passwd
