#!/usr/bin/env bash

# The file /etc/passwd has already been covered in a previous project and you should be familiar with it. Today we will make up a story based on it.

# Write a Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.

# Format: The user USERNAME is part of the GROUP_ID gang, lives in HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO

# Requirements:

    # You must use the while loop (for and until are forbidden)


IFS=:
while read -r username user_id group_id home_dir command shell password user_info
do
    echo "The user $username is part of the $group_id gang, lives in $home_dir and rides $command/$shell."
    echo "$username's place is protected by the passcode $password, more info about the user here: $user_info"
    echo ""
done < /etc/passwd
