#!/usr/bin/env bash

# Now that you’ve parsed the Apache log file, let’s sort the data so you can get a better idea of what is going on.

# Using what you did in the previous exercise, write a Bash script that groups visitors by IP and HTTP status code, and displays this data.

# Requirements:

    # The exact format must be:
        # OCCURENCE_NUMBER IP HTTP_CODE
        # In list format
    # Ordered from the greatest to the lowest number of occurrences
        # See example
    # You must use awk
    # You are not allowed to use while, for, until and cut


# Store the sorted data in a variable
sortedData=$(awk '{print $1 " " $9}' access.log | sort | uniq -c | sort -nr)

# Loop through each line of the sorted data
while read -r line; do
  # Get the count, IP, and HTTP code from the line
  count=$(echo $line | awk '{print $1}')
  ip=$(echo $line | awk '{print $2}')
  httpCode=$(echo $line | awk '{print $3}')

  # Display the data in the desired format
  echo "$count $ip $httpCode"
done <<< "$sortedData"
