#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# initialize the counter
count=1

# Use a until loop to iterate until the counter is greater than 10

until [ $count -gt 10 ]; do
	echo "Best School"
	count=$((count + 1))
done
