#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

#initialize the counter

count=1

# Use a while loop to iterate 10 times
while [ $count -le 10 ]; do
	if [ $count -eq 9 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	count=$((count + 1 ))
done
