#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
  
# Write a Bash script that loops from 1 to 10 and:

# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations

# initialize the counter
count=1
while [ $count -le 10 ]; do
    if [ $count -eq 4 ]; then
        echo "Bad luck"
    elif [ $count -eq 8 ]; then
        echo "Good luck"
    else
        echo "Best School"
    fi
    count=$((count+1))
done

