#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

#displays the time for 12 hours and 59 minutes:

#display hours from 0 to 12
#display minutes from 1 to 59

# initialize the hour

i="0"
while [ "$i" -le $((60 * 12 + 59)) ]; do
	if [ $((i % 60)) -eq 0 ]; then
		echo "Hour: $((i / 60))"
	else
		echo "$((i % 60))"
	fi;
	i=$((i + 1))
done;
