#!/usr/bin/env bash


# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed (refer to the example)
# Requirements:	    
# You must use the for loop (while and until are forbidden)
# Do not display hidden filesthe counter

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
